create table if not exists customer (
	id bigint generated by default as identity,
	first_name varchar(255),
	last_name varchar(255),
	primary key (id)
);

create table if not exists transaction (
	id bigint generated by default as identity,
	bill_date date,
	bill_amt double,
	customer_id bigint,
	primary key (id),
	CONSTRAINT FK_TRANSACTION_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID)
);

